FROM python:3.10-slim

WORKDIR /app

COPY brookyapi/requirements.txt .

RUN pip install -r requirements.txt

COPY brookyapi/ .
COPY brooksai/agent/ /app/brooksai/agent/


ENTRYPOINT [ "python" ]
CMD ["main.py"]