FROM python:3.10-slim

WORKDIR /app

COPY brookyapi/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY brookyapi/ .
COPY brooksai/agent/ /app/brooksai/agent

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app