name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker europe-west2-docker.pkg.dev

    - name: Build docker image
      run:  docker build -t europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/brookyapi-repo/brooky-api -f brookyapi/dockerfile .
    
    - name: Push docker image
      run: docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/brookyapi-repo/brooky-api
    
    - name: Deploy to Cloud Run
      run: gcloud run deploy brooky-api --image europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/brookyapi-repo/brooky-api --platform managed --region europe-west2 --allow-unauthenticated --memory 1Gi